###########################################################################
# This is a sample Azure DevOps pipeline that can be used for validating 
# documentation. In this pipeline we use markdownlint and the DocLinkChecker tool.
###########################################################################
trigger: none

pool:
  vmImage: windows-latest

jobs:
# Scan markdownfiles on style consistency
- job:
  displayName: 'Execute Markdownlint'
  steps:
    - bash: npm install -g markdownlint-cli
      displayName: 'Install markdownlint'

    - bash: markdownlint -c $CONFIGFILE $WORKDIR
      env:
        WORKDIR: $(System.DefaultWorkingDirectory)
        CONFIGFILE: $(System.DefaultWorkingDirectory)/.markdownlint.json
      displayName: 'Run markdownlint'

# install the companion tools
- powershell: choco install docfx-companion-tools -y
  displayName: Install docfx companion tools

# run the toc generator on /DocExamample folder
- powershell: DocLinkChecker -d .\DocExamples -a
  displayName: 'Checking links in .\DocExamples'
