# Workflow triggered by push to main
# For all solutions we run restore, build & test
name: Build & Test

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    
    # Loop through all the solutions in src and restore, build & test
    - name: Restore, build & test
      shell: pwsh
      run: |
        foreach ($sln in (Get-ChildItem -Recurse src\*.sln)) {
          Write-Host "Start building $($sln.FullName)"

          & dotnet restore $sln.FullName
          & dotnet build $sln.FullName --no-restore
          & dotnet test $sln.FullName --no-build --verbosity normal
        }
